quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=stok
quarkus.datasource.password=kamvas
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/stok_db

quarkus.hibernate-orm.database.generation=update

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization