CREATE TABLE suppliers (
    id UUID PRIMARY KEY,
    code BIGSERIAL UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    document VARCHAR(255) UNIQUE NOT NULL,
    category VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);