ALTER TABLE suppliers
ADD COLUMN person_type VARCHAR(2) NOT NULL DEFAULT 'PJ',
ADD COLUMN contact_name VARCHAR(150),
ADD COLUMN email VARCHAR(150),
ADD COLUMN phone VARCHAR(30),
ADD COLUMN address VARCHAR(180),
ADD COLUMN zip_code VARCHAR(20),
ADD COLUMN city VARCHAR(80),
ADD COLUMN neighborhood VARCHAR(80);